#Ansible Playbook
#Pip Conf

#command to execute: ansible-playbook -v -i /etc/ansible/hosts /etc/ansible/playbooks/Add_pip.yml --ask-become-pass

- hosts: workstations
  user: <uname> #user who has root access#
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  tasks:
    
    - name: Create PIP
      file: 
        path: "/home/{{ item }}/.config/pip/"
        state: directory
        owner: "{{ item }}"
        group: TEST
      with_items:
        - minjs
        - TEST
   
    - name: Delete existing PIP.conf  
      file:
        path: "/home/{{ item }}/.config/pip/pip.conf"
        state: absent
        owner: "{{ item }}"
        group: TEST
      with_items:
        - minjs
        - TEST

    - name: Create new PIP conf
      file:
        path: "/home/{{ item }}/.config/pip/pip.conf"
        state: touch
        owner: "{{ item }}"
        group: TEST
        mode: 0600
      with_items:
        - minjs
        - TEST

    - lineinfile:
        path: "/home/{{ item }}/.config/pip/pip.conf"
        state: present
        line: '[global]'
        backup: yes
        owner: "{{ item }}"
        group: TEST
      with_items:
        - minjs
        - TEST
       
    - lineinfile:
        path: "/home/{{ item }}/.config/pip/pip.conf"
        state: present
        insertafter: '[global]'
        line: 'index-url = http://<repo server>/bandersnatch/mirror/web/simple'
        backup: yes 
        owner: "{{ item }}"
        group: TEST
      with_items:
        - minjs
        - TEST
        
    - lineinfile:
        path: "/home/{{ item }}/.config/pip/pip.conf"
        state: present
        insertafter: 'index-url = http://<repo server>/bandersnatch/mirror/simple'
        line: '[install]'
        backup: yes  
        owner: "{{ item }}"
        group: TEST
      with_items:
        - minjs
        - TEST
 
    - lineinfile:
        path: "/home/{{ item }}/.config/pip/pip.conf"
        state: present
        insertafter: '[install]'
        line: 'trusted-host = <repo server>'
        backup: yes
        owner: "{{ item }}"
        group: TEST
      with_items:
        - minjs
        - TEST
       
