#Ansible Playbook
#APT Installation

#command to exeute: ansible-playbook -v -i /etc/ansible/hosts/ APT_plybk.yml --ask-become-pass

- hosts: localhost #sets to run on the local host you can input a server group within the host file to hit multiple nodes
  user: <uname> #user who has root access#
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  tasks:

    - name: add repo
      apt_repository: repo='deb [arch=amd64] http://<repo addr>/ubuntu bionic main restricted universe multiverse'
      apt_repository: repo='deb [arch=amd64] http://<repo addr>/ubuntu bionic-security main restricted universe multiverse'
      apt_repository: repo='deb [arch=amd64] http://<repo addr>/ubuntu bionic-updates main restricted universe multiverse'

    - name: install packages
      apt:
        name: "{{ item }}"
        state: present
#add new apt to the list below for it to be installed
      with_items:
        - 'locales'
        - 'build-essential'
        - 'acl'
        - 'htop'
        - 'git'
        - 'supervisor'
        - 'python-pip'
        - 'python3-pip'
        - 'nginx'
        - 'aptitude'
        - 'cmake'
        - 'make'
        - 'gcc'
        - 'g++'
        - 'flex'
        - 'bison'
        - 'libpcap-dev'
        - 'libssl-dev'
        - 'python-dev'
        - 'swig'
        - 'zlib1g-dev'
        - 'swig3.0'
        - 'dislocker'
        - 'docker'
        - 'docker.io'
        - 'python-docker'
        - 'net-tools'

    - name: run apt-get update and upgrade
      apt: 
       state: latest
       upgrade: yes
       update_cache: yes
       cache_valid_time: 86400

    - name: reload daemon
      shell: systemctl daemon-reload 
