
#Ansible Playbook
#Modify Ulimits this is a necessary step in order to install Splunk

#command to exeute: ansible-playbook -v -i /etc/ansible/hosts/ modify_ulimit.yml --ask-become-pass

- hosts: workstations
  user: <uname> #user who has root access#
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  tasks:

    - lineinfile:
        path: /etc/systemd/user.conf
        regexp: '^#DefaultLimitNOFILE='
        line: 'DefaultLimitNOFILE=65536'
        backup: yes
        owner: 
        group:    
        backrefs: yes

    - lineinfile:
        path: /etc/systemd/user.conf
        state: present
        regexp: '^#DefaultLimitNPROC='
        line: 'DefaultLimitNPROC=65536'
        backup: yes
        owner: 
        group: 
        backrefs: yes

    - lineinfile:
        path: /etc/systemd/user.conf
        regexp: '^#DefaultLimitMEMLOCK='
        line: 'DefaultLimitMEMLOCK=unlimited'
        backup: yes
        owner: 
        group: 
        backrefs: yes

    - lineinfile:
        path: /etc/sysctl.conf            
#        regexp: '^fs.file-max='
        insertafter: '#fs.protected_symlinks=0'
        line: 'fs.file-max = 100000'
        backup: yes
        owner: root
        group: root
#        backrefs: yes

    - lineinfile:
        path: /etc/sysctl.conf
        insertafter: 'fs.file-max = 100000'
        line: 'fs.inotify.max_user_watches = 524288'
        backup: yes
        owner: root
        group: root
        backrefs: yes

    - lineinfile:
        path: /etc/systemd/system.conf        
        regexp: '^#DefaultLimitNOFILE='
        line: 'DefaultLimitNOFILE=65536'
        backup: yes
        owner: root
        group: root
        backrefs: yes

    - lineinfile:
        path: /etc/systemd/system.conf
        regexp: '^#DefaultLimitNPROC='
        line: 'DefaultLimitNPROC=65536'
        backup: yes
        owner: root
        group: root
        backrefs: yes

    - lineinfile:
        path: /etc/systemd/system.conf
        regexp: '^#DefaultLimitMEMLOCK='
        line: 'DefaultLimitMEMLOCK=unlimited'
        backup: yes
        owner: root
        group: root     
        backrefs: yes

    - name: configure system settings, file descriptors and number of threads to TEST   
      pam_limits:  
       domain: TEST
       limit_type: "{{item.limit_type}}"
       limit_item: "{{item.limit_item}}"
       value: "{{item.value}}"
      with_items:
         - { limit_type: 'soft', limit_item: 'nofile', value: 65536 }
         - { limit_type: 'hard', limit_item: 'nofile', value: 65536 }
         - { limit_type: 'soft', limit_item: 'nproc', value: 65536 }
         - { limit_type: 'hard', limit_item: 'nproc', value: 65536 }
         - { limit_type: 'soft', limit_item: 'memlock', value: unlimited }
         - { limit_type: 'hard', limit_item: 'memlock', value: unlimited }

    - name: configure system settings, file descriptiors and number of threads to ROOT        
      pam_limits:
       domain: root
       limit_type: "{{item.limit_type}}"
       limit_item: "{{item.limit_item}}"
       value: "{{item.value}}"
      with_items:
        - { limit_type: 'soft', limit_item: 'nofile', value: 65536 }
        - { limit_type: 'hard', limit_item: 'nofile', value: 65536 }
        - { limit_type: 'soft', limit_item: 'nproc', value: 65536 }
        - { limit_type: 'hard', limit_item: 'nproc', value: 65536 }
        - { limit_type: 'soft', limit_item: 'memlock', value: unlimited }
        - { limit_type: 'hard', limit_item: 'memlock', value: unlimited }
  
    - name: install sysfsutils for disabling transparent huge pages
      package:
        name: sysfsutils
        state: latest
    
    - name: disable transparent huge pages for redis performance - persistent change
      lineinfile:
        path: /etc/sysfs.conf
        create: true
        regexp: '^kernel\/mm\/transparent\_hugepage\/enabled'
        line: "kernel/mm/transparent_hugepage/enabled = never"
    
    - name: disable transparent huge pages for redis performance - live change
      shell: echo never {{ ">" }} /sys/kernel/mm/transparent_hugepage/enabled
    
    - name: Rebooting after configuration changes
      reboot:
       msg: "Reboot initiated by Ansible"
