#Ansible Playbook
#Implementing Password Policy

#command to execute: ansible-playbook -v -i /etc/ansible/hosts /etc/ansible/playbooks/pw_policy.yml --ask-become-pass

- hosts: workstations
  user: <username>
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  tasks:

      - name: Install Password Quality Checker
        apt: 
          name: libpam-pwquality
          state: present

      - name: Creating password policy in /etc/pam.d/common-password
        remote_user: <username>
        become: yes
        become_method: sudo
        pamd:
          name: common-password
          type: password
          control: '[success=1 default=ignore]'
          module_path: pam_unix.so
          new_type: password
          new_control: requisite
          new_module_path: pam_pwquality.so
          state: before

      - name: Implementing Password policy in /etc/pam.d/common-password
        remote_user: <username>
        become: yes
        become_method: sudo
        pamd:
         name: common-password
         type: password
         control: requisite
         module_path: pam_pwquality.so
         module_arguments:
           - retry=3
           - minlength=8
           - ucredit=-1
           - lcredit=-1
           - dcredit=-1
           - ocredit=-1
         state: args_present
           
