#Ansible Playbook
#Password Replication

#Grab new password from whatever workstation that the user changed it on. Once you have the newly created password replace the line with the new hashed password in /etc/shadow
#Command to execute: anisble-playbook -v -i /etc/ansible/hosts /etc/ansible/playbooks/pw_rep.yml --ask-become-pass 

- hosts: workstations
  user: root #or user who has root access#
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  tasks:

    - name: Adding new password for "TEST" to SHADOW
      lineinfile:      
        path: /etc/shadow
        regexp: '^TEST:'
        insertafter: 'TEST:'
        line: 'TEST:<pw hash>:18163:7:90:14:30::'
        state: present
        backrefs: yes
        owner: root
        group: root
        
    - name: Adding new password for "minjs" to SHADOW
      lineinfile:
        path: /etc/shadow
        regexp: '^minjs:'
        insertafter: 'minjs:'
        line: 'minjs:<pw hash>:18184:0:99999:7:::'
        state: present
        backrefs: yes
        owner: root
        group: root
