- hosts: splunk_searchhead
  user: root #or user who has root access#
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  tasks:

    - name: Replicating password for "minjs" to SPLUNK
      lineinfile:
        path: /opt/splunk/etc/passwd
        regexp: '^:minjs:'
        insertafter: ':minjs:'
        line: ':minjs:<pw hash>::Administrator:admin:admin@example.com:::18169'
        state: present
        backrefs: yes
        owner: root
        group: root

    - name: Replicating password for "TEST" to SPLUNK
      lineinfile:
        path: /opt/splunk/etc/passwd
        regexp: '^:TEST:'
        insertafter: ':TEST:'
        line: ':TEST:<pw hash>::Administrator:admin:admin@example.com:::18142'
        state: present
        backrefs: yes
        owner: root
        group: root

