#Ansible Playbook
#User Deletion

#command to execute: ansible-playbook -v -i /etc/ansible/hosts /etc/ansible/playbooks/user_deletion.yml --ask-become-pass

- hosts: workstations
  user: root #or user who has root access#
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  tasks:

#        - name: remove user "ANSIBLE TEST"
#          remote_user: cyote
#          become: yes
#          become_method: sudo
#          become_user: root
#          user:
#            name: ansibletst
#            state: absent
#           remove: yes
#           force: yes

       - name: Removing user "John Min"
          remote_user: <adminuser>
          become: yes
          become_method: sudo
          become_user: root
          user:
            name: minjs
            state: absent
            remove: yes
            force: yes
